Trim down Apache config, start and configure memcached
We only need the backoffice for now, remove all unneeded Apache configurations.
memcached needs to be started and is available on localhost:11211 by default.
The server name needs to be set in the ENV variable via Apache configuration:
* http://wiki.koha-community.org/wiki/Cache_handling_in_Koha
* http://wiki.koha-community.org/wiki/Performance#Memcache

Fixes:

Software error:

Bad arg length for Socket::pack_sockaddr_in, length is 0, should be 4 at /usr/lib64/perl5/vendor_perl/Socket.pm line 834.
BEGIN failed--compilation aborted at C4/Context.pm line 98.
Compilation failed in require at C4/Output.pm line 33.
BEGIN failed--compilation aborted at C4/Output.pm line 33.
Compilation failed in require at /var/www/cgi-bin/koha/mainpage.pl line 24.
BEGIN failed--compilation aborted at /var/www/cgi-bin/koha/mainpage.pl line 24.