Add memcached too, it's required
Software error:

Can't locate Cache/Memcached.pm in @INC (you may need to install the Cache::Memcached module) (@INC contains: __PERL_MODULE_DIR__ /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at C4/Context.pm line 85.
BEGIN failed--compilation aborted at C4/Context.pm line 98.
Compilation failed in require at C4/Output.pm line 33.
BEGIN failed--compilation aborted at C4/Output.pm line 33.
Compilation failed in require at /var/www/cgi-bin/koha/mainpage.pl line 24.
BEGIN failed--compilation aborted at /var/www/cgi-bin/koha/mainpage.pl line 24.