Add perl-GD to avoid fatail in catalogue/detail.pl
Software error:

Can't locate GD.pm in @INC (you may need to install the GD module) (@INC contains: __PERL_MODULE_DIR__ /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/share/perl5/vendor_perl/C4/Images.pm line 26.
BEGIN failed--compilation aborted at /usr/share/perl5/vendor_perl/C4/Images.pm line 26.
Compilation failed in require at /usr/share/koha/intranet/cgi-bin/catalogue/detail.pl line 40.
BEGIN failed--compilation aborted at /usr/share/koha/intranet/cgi-bin/catalogue/detail.pl line 40.